### ISSUE TITLE
Jasmine?

### ISSUE THREAD

**Issue by tisdall** [phonegap/phonegap-template-hello-world#24]
I'm new to PhoneGap so excuse my ignorance...

I started my own project and noticed the "jasmine" files but I'm not really sure the purpose of those files.  They don't seem to be linked to index.html and it seems like it's safe for me to just delete them and exclude them from my project.  Are they there to help with developing a testing framework?

**Comment by purplecabbage** [comment]
Yeah, you can delete them.  This is the test framework we use elsewhere, so if you wanted to add tests to your app you could. :)
