### ISSUE TITLE
Ideas for config.xml cleanup

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-template-hello-world#3]
We can't document the **config.xml** file through comments since they do not come thru in the generated xml file when the user gets this project as a base. Maybe it would be better to have a more basic, default config.xml file with the common properties used with the CLI included only (`DisallowOverscroll` etc). Most of the properties in the default project now are specific to PhoneGap Build and confuse people only using the CLI. 

Then maybe we could also create a new **config.md** (or readme) that documents them all and/or points to the interactive reference guide here: http://devgirl.org/files/config-app/. We could also point out the PGB ones specifically rather than include them every time as the default as we are now. 

Another option is to use the command line to prompt and ask if they're using PGB after they type the basic `create` command (before the project is downloaded) and include a config.xml with those properties specific to the tool they're building with.

**Comment by devgeeks** [comment]
@hollyschinsky is this issue still relevant since the big changes made recently?

**Comment by hollyschinsky** [comment]
No, thanks for the heads up, closing.
