### ISSUE TITLE
After build, apk fails to install on android.

### ISSUE THREAD

**Issue by JakeRuth** [phonegap/phonegap-template-hello-world#4]
I was developing using phonegap build when my installs started to fail on my device, these are the steps I use to product the problem.
-create new app (in phonegap)
-link it to this repo
-build all
-use qr reader to download apk onto my android device
-download file from s3
-open file
-select download
-prompted with message "App not Installed"

Any ideas?

**Comment by yunusemreuveyik** [comment]
ı dont know about qr but ı used barcode scanner and installed properly like asking the permissions and stuffs. maybe you can try this way ıdk

**Comment by devgeeks** [comment]
I am closing this issue as stale. If it's still a problem, please feel free to reopen.

**Comment by pk936** [comment]
I am also facing the same issue.
