### ISSUE TITLE
Viewport target-densitydpi is deprecated

### ISSUE THREAD

**Issue by jessemonroy650** [phonegap/phonegap-template-hello-world#7]
The index.html still has the tag `target-densitydpi`.
In addition, some examples still have it. Namely,
http://docs.phonegap.com/develop/hello-world-explained/

http://www.petelepage.com/blog/2013/02/viewport-target-densitydpi-support-is-being-deprecated/

This issue comes up on a regular basis.
https://groups.google.com/forum/#!topic/phonegap/kDoP0PIF9qM

**Comment by jcesarmobile** [comment]
+1

As phonegap CLI and phonegap Desktop apps are created from this template this should be fixed.  
I think height=device-height should be removed too as it usually causes problems on some devices.

cordova template uses this tag

` <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">`

**Comment by chrisgriffith** [comment]
The tag is now:
 <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

**Comment by jcesarmobile** [comment]
You forgot to put it as code

The tag is now:
`<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
    `

**Comment by saikatghosh1978** [comment]
<meta name="viewport" content="width=device-width, target-densitydpi=device-dpi, initial-scale=0">
Meta viewport not working in IOS devices.
my application is fix with application.
It's working fine in Android devices.

**Comment by M4TH76** [comment]
+1 iOS not working
